routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// use App\Http\Controllers\Admin\UserController;
// use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\SendMailController;
use App\Http\Controllers\Admin\CMSController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::get('education-outreach', 'Api\DocumentController@education_outreach');
Route::get('about-us', 'Api\DocumentController@about_us');
Route::get('contact-us', 'Api\DocumentController@contact_us');
Route::get('internet-based-ads', 'Api\DocumentController@internet_based_ads');
Route::get('privacy-notice', 'Api\DocumentController@privacy_notice');
Route::get('term-of-service', 'Api\DocumentController@term_of_service');

Route::post('add-channel-id', 'CommonController@add_channel_id');
Route::get('account-activation/{id}', 'CommonController@account_activation');
Route::any('create/password/{id}/{token}', 'CommonController@craete_password')->name('create.password');
Route::get('auth-account-activation/{id}', 'CommonController@auth_account_activation');

Route::post('forgot/password', 'CommonController@forgot_password')->name('forgot_password');
Route::get('store-forgot-password', 'CommonController@store_forgot_password')->name('store.forgot');
Route::get('board-forgot-password', 'CommonController@board_forgot_password')->name('board.forgot');


Route::get('add-channel-id', 'CommonController@add_channel_id');
Route::get('terms-conditions', 'CommonController@terms_conditions');
Route::get('privacy-policy', 'CommonController@privacy_policy');
Route::get('logs/{id}', 'CommonController@activity_log');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function () {

    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');

    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/show/{id}', 'UserController@show')->name('user.show');
    Route::get('users/edit/{id}', 'UserController@edit')->name('user.edit');
    Route::put('users/update/{id}', 'UserController@update')->name('user.update');
    Route::get('users/destroy/{id}', 'UserController@edit')->name('user.destroy');
    Route::post('active_deactive','UserController@active_deactive')->name('active_deactive');

    Route::post('active_deactive_school','SchoolController@active_deactive_school')->name('active_deactive_school');

    Route::post('active_deactive_genre','CategoryController@active_deactive_genre')->name('active_deactive_genre');
      
    Route::resource('category',CategoryController::class);
    Route::resource('season',SeasonController::class);
    Route::resource('ratings',AgeRatingController::class);
    Route::resource('tags',TagController::class);
    Route::resource('artist',ArtistController::class);
    Route::resource('genre',GenreController::class);
    Route::resource('cast',CastTypeController::class);
    Route::resource('plan',PlanController::class);  
    Route::resource('attribute',AttributeController::class);  
    Route::resource('measurement',MeasurementController::class);    
    Route::resource('contactus',ContactUsController::class);    
    Route::resource('issue',IssueController::class);    
    Route::resource('grade',GradeController::class);    
    Route::resource('orders',OrderController::class);  
    Route::resource('content',ContentController::class);    
    Route::resource('video',VideoController::class);    
    Route::resource('faq',FaqController::class);    
    Route::resource('feedback',FeedbackController::class);    
    
    Route::any('adv_content_change', 'ContentController@adv_content_change')->name('adv_content_change');
    Route::any('child_adv_content_change', 'ContentController@child_adv_content_change')->name('child_adv_content_change');
    Route::get('get_season_data', 'VideoController@get_season_data')->name('get_season_data');   
    Route::post('trailer_file_upload', 'ContentController@trailer_file_upload')->name('trailer_file_upload');   
    Route::post('chunk_file_upload', 'VideoController@chunk_file_upload')->name('chunk_file_upload');   
    Route::post('active_deactive_faq','FaqController@active_deactive_faq')->name('active_deactive_faq');

    Route::get('plan/manageattr/{id}', 'PlanController@manageattr')->name('plan.manageattr');   
    Route::post('plan/attr_update/{id}', 'PlanController@attr_update')->name('plan.attr_update');   
    
    Route::post('product/addstore/{id}', 'ProductController@addstore')->name('product.addstore');   
    Route::get('remove_product_store/{id}', 'ProductController@remove_product_store')->name('remove_product_store');   
    Route::post('save_product_store', 'ProductController@save_product_store')->name('save_product_store');   
    Route::post('active_deactive_product','ProductController@active_deactive_product')->name('active_deactive_product');
    Route::post('get_image','ProductController@get_image')->name('get_image');

    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');
    
    Route::get('reported/issue','IssueController@reported_issue_index')->name('reported.issue');
    Route::get('bulk/notification',[NotificationController::class,'index'])->name('bulk.index');
    Route::post('bulk/notification',[NotificationController::class,'store'])->name('bulk.store');
    
    Route::get('system/config','SystemConfigController@index')->name('system.config');
    Route::post('system/config/submit','SystemConfigController@update')->name('system.config.submit');
    Route::post('system/config/backup','SystemConfigController@update')->name('system.config.backup');
    Route::post('system/config/download','SystemConfigController@update')->name('system.config.download');
    Route::post('system/config/delete_backup','SystemConfigController@update')->name('system.config.delete_backup');
    
    Route::get('app/config','SystemConfigController@app')->name('app.config');
    Route::post('app/config/submit','SystemConfigController@submit_app')->name('app.config.submit');

    Route::get('report/all_report','ReportController@index')->name('report.all');

    Route::get('order/all_orders','OrderController@all_orders')->name('order.all');

    Route::get('order/create_order','OrderController@create_order')->name('order.create');

    Route::post('order/get_user','OrderController@get_user')->name('order.get_user');
    Route::post('order/get_meal','OrderController@get_meal')->name('order.get_meal');
    Route::post('order/get_meal_details','OrderController@get_meal_details')->name('order.get_meal_details');
    Route::post('order/book_meal','OrderController@book_meal')->name('order.book_meal');

    Route::get('order/refund','OrderController@refund')->name('order.refund');
    Route::get('order/all_orders/view/{id}','OrderController@all_orders_view')->name('order.all.view');
    Route::post('refund','OrderController@refund_test')->name('refund');

    Route::any('send-mail-customer',[SendMailController::class,'customer'])->name('mail.customer');
    Route::any('send-notification-customer',[SendMailController::class,'customer_notification'])->name('notification.customer');

    Route::any('terms-conditions',[CMSController::class,'terms_conditions'])->name('terms_conditions');
    Route::any('privacy-policy',[CMSController::class,'privacy_policy'])->name('privacy_policy');
});
Route::group(['namespace' => 'Board', 'prefix' => 'board', 'as' => 'board.', 'middleware' => ['auth', 'board']], function () {
    
    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');
    
    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('active_deactive_category','CategoryController@active_deactive_category')->name('active_deactive_category');
    Route::resource('category', CategoryController::class);
    Route::resource('store', StoreController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('product', ProductController::class);
    Route::resource('orders',OrderController::class);
    Route::resource('meal', MealController::class);
    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');

    Route::get('report/all_report','ReportController@all_report')->name('report.all');
    
    Route::get('order/all','OrderController@all')->name('order.all');
    Route::get('order/all/view/{id}','OrderController@all_orders_view')->name('order.all.view');

    Route::get('order/inprocess','OrderController@inprocess')->name('order.inprocess');
    Route::get('order/inprocess/view/{id}','OrderController@inprocess_view')->name('order.inprocess.view');
    Route::get('order/inprocess/edit/{id}','OrderController@inprocess_edit')->name('order.inprocess.edit');
    Route::post('order/inprocess/item/update','OrderController@item_update')->name('order.item.update');
    Route::post('order/inprocess/date/update','OrderController@date_update')->name('order.date.update');

app/Http/Controllers/Board/BannerController.php
<?php

namespace App\Http\Controllers\board;

use App\Http\Controllers\Controller;
use App\Helpers\CommonHelper;
use Illuminate\Http\Request;
use App\Models\Banner;
use App\Models\User;
use DataTables;
use Illuminate\Support\Facades\Auth;


class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
           
           
       if ($request->ajax())
       {
            
             $login_id =  Auth::user()->id;
            $data = Banner::select('*')->where('user_id',$login_id)->orderBy('id','desc')->with('user_name')->get();
            return Datatables::of($data)
            ->addIndexColumn()

            ->addColumn('user_data', function($row) {
                    
                    $user_data = $row['user_id'];
                    return  $user_data;
                })

            ->addColumn('start_date', function($row) {
                
                $start_date= date('m-d-Y', strtotime($row['start_date']));
                return $start_date;
            })

             ->addColumn('end_date', function($row) {
                
                $end_date= date('m-d-Y', strtotime($row['end_date']));
                return $end_date;
            })
            
            ->editColumn('image', function ($row) {
                return '<img class="border rounded p-0" src="'.$row['image'].'" onerror="this.src=/images/default.png" alt="your image" style="height: 70px;width: 100px; object-fit: cover;" id="blah1"/>';
            })
           
            ->editColumn('action', function ($row)
            {
               $btn = '<a href="'.route('board.banner.show',$row['id']).'" class="mr-2"><i class="fa fa-eye"></i></a>';
               // $btn .= '<a href="'.route('board.banner.destroy', $row['id']).'" data-url="banner" data-id="'.$row["id"].'" data-popup="tooltip" onclick="delete_notiflix(this);return false;" data-token="'.csrf_token().'" ><i class="fa fa-trash"></i></a>';
               return $btn;
            })
            ->rawColumns(['image','user_data', 'action'])
            ->make(true);
       }
       else
       {
           $columns = [
            //    ['data' => 'sequence', 'name' => 'sequence','title' => __("Sequence")],
               ['data' => 'id','name' => 'id','title' => "Id"], 
               ['data' => 'image','name' => 'image', 'title' => __("Image"),'searchable'=>false],
               ['data' => 'start_date','name' => 'start_date', 'title' => __("Start Date"),'searchable'=>true],
               ['data' => 'end_date','name' => 'end_date', 'title' => __("End Date"),'searchable'=>true],
               ['data' => 'action', 'name' => 'action','title' => "Action",'searchable'=>false,'orderable'=>false]];
           $params['dateTableFields'] = $columns;
           $params['dateTableUrl'] = route('board.banner.index');
           $params['dateTableTitle'] = "Banner";
           $params['dataTableId'] = time();
           $params['addUrl'] = route('board.banner.create');
           return view('board.pages.banner.index',$params);
       }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $params['pageTittle'] = "View Banner";
        $banner =Banner::find($id);
        // dd($banner);
        $params['banner'] = $banner->toArray();
        $params['backUrl'] = route('board.banner.index');
        return view('board.pages.banner.view',compact('banner'),$params);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Board/DashboardController.php
<?php
namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use CommonHelper;
use Illuminate\Support\Facades\Auth;
use App\Models\Category;
use App\Models\Product;
use App\Models\Meal;
use App\Models\User;
use App\Models\Orders;
use App\Models\StoresProduct;

class DashboardController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {

        $login_id =  Auth::user()->id;
        // dd($login_id);
        $store = User::select('id')->where('parent_id',$login_id)->get()->pluck('id')->toArray();
        // dd($store); 
        $orders_completed=Orders::whereIn('store_id',$store)->where('status','6')->count();
        // dd($orders);
        
        $total=Orders::whereIn('store_id',$store)->sum('total');

        $customers=User::where('parent_id',$login_id)->count();

        
        $orders = Orders::whereIn('store_id',$store)->count();
        // dd($orders);
        
        $params['store'] = User::select('*')->where('parent_id',$login_id)->count();
        // dd($params['store']);
        $params['product'] = Product::count();
        return view('board.pages.dashboard',compact('orders_completed','total','customers','orders'),$params);
    }
}

resources/views/board/pages/dashboard.blade.php
@extends('board.layouts.master')
@section('content')
<!-- Start Content-->
<div class="container-fluid">
    
    <!-- start page title -->
    @include('board.include.flash-message')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    
                </div>
                <h4 class="page-title">Dashboard</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->
    
    <div class="row">
        <div class="col-md-6 col-xl-3">
            <div class="widget-rounded-circle card-box">
                <div class="row">
                    <div class="col-6">
                        <div class="avatar-lg rounded-circle  border-danger border">
                            <i class="fe-dollar-sign font-22 avatar-title text-danger"></i>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="text-right">
                            <h3 class="text-dark mt-1"><span data-plugin="counterup">{{$total}}</span></h3>
                            <p class="text-muted mb-1 text-truncate">Total Earnings</p>
                        </div>
                    </div>
                </div> <!-- end row-->
            </div> <!-- end widget-rounded-circle-->
        </div>

      

        <div class="col-md-6 col-xl-3">
            <div class="widget-rounded-circle card-box">
                <div class="row">
                    <div class="col-6">
                        <div class="avatar-lg rounded-circle border-warning border">
                            <i class="fas fa-store font-22 avatar-title text-warning"></i>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="text-right">
                            <h3 class="text-dark mt-1"><span data-plugin="counterup">{{$store}}</span></h3>
                            <p class="text-muted mb-1 text-truncate">Total Stores</p>
                        </div>
                    </div>
                </div> <!-- end row-->
            </div> <!-- end widget-rounded-circle-->
        </div> <!-- end col-->
        <div class="col-md-6 col-xl-3">
            <div class="widget-rounded-circle card-box">
                <div class="row">
                    <div class="col-6">
                        <div class="avatar-lg rounded-circle border-info border">
                            <i class="fe-users font-22 avatar-title text-info"></i>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="text-right">
                            <h3 class="text-dark mt-1"><span data-plugin="counterup">{{$customers}}</span></h3>
                            <p class="text-muted mb-1 text-truncate">Total Customer</p>
                        </div>
                    </div>
                </div> <!-- end row-->
            </div> <!-- end widget-rounded-circle-->
        </div> 

        <div class="col-md-6 col-xl-3">
            <div class="widget-rounded-circle card-box">
                <div class="row">
                    <div class="col-6">
                        <div class="avatar-lg rounded-circle border-primary  border">
                            <i class="fe-shopping-cart font-22 avatar-title text-primary"></i>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="text-right">
                            <h3 class="text-dark mt-1"><span data-plugin="counterup">{{$orders_completed}}</span></h3>
                            <p class="text-muted mb-1 text-truncate">Total Completed Orders</p>
                        </div>
                    </div>
                </div> <!-- end row-->
            </div> <!-- end widget-rounded-circle-->
        </div> 
        <div class="col-md-6 col-xl-3">
            <div class="widget-rounded-circle card-box">
                <div class="row">
                    <div class="col-6">
                        <div class="avatar-lg rounded-circle border-primary border">
                            <i class="fe-shopping-cart font-22 avatar-title text-primary"></i>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="text-right">
                            <h3 class="text-dark mt-1"><span data-plugin="counterup">{{$orders}}</span></h3>
                            <p class="text-muted mb-1 text-truncate">Total Orders</p>
                        </div>
                    </div>
                </div> <!-- end row-->
            </div> <!-- end widget-rounded-circle-->
        </div> 
    </div>
    <!-- end row -->
    
    </div> <!-- container -->
    @endsection

resources/views/board/pages/profile.blade.php
@extends('board.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('profile')}}
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
		</div>
	</div>
    @include('board.include.flash-message')
    <div class="row">
        <div class="col-lg-4 col-xl-4">
            <div class="card-box text-center">
                <img src="{{ URL::to($user['profile_picture'])}}" class="rounded-circle avatar-lg img-thumbnail"
                    alt="profile-image">

                <h4 class="mb-0">{{$user['first_name']}} </h4>
                <p class="text-muted">{{$user['email']}}</p>

                <div class="text-left mt-3">
                    <p class="text-muted mb-2 font-13"><strong>Board Name :</strong> <span class="ml-2">{{$user['first_name']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Phone :</strong><span class="ml-2">{{$user['phone_formatted']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Email :</strong> <span class="ml-2">{{$user['email']}}</span></p>
                    
                    <!-- <p class="text-muted mb-2 font-13"><strong>Gender :</strong> <span class="ml-2">{{$user['gender'] == '1' ? 'Male' : 'Female'}}</span></p> -->

                    <!-- <p class="text-muted mb-2 font-13"><strong>DOB :</strong> <span class="ml-2">{{ $user['dob'] }}</span></p> -->
                    <!-- 
                    <p class="text-muted mb-2 font-13"><strong>Department :</strong> <span class="ml-2">{{ $user['department'] }}</span></p>
                    <p class="text-muted mb-2 font-13"><strong>Grade :</strong> <span class="ml-2">{{ $user['grade'] }}</span></p>
                    <p class="text-muted mb-2 font-13"><strong>Class :</strong> <span class="ml-2">{{ $user['class'] }}</span></p> -->
                </div>
            </div> <!-- end card-box -->


        </div> <!-- end col-->

        <div class="col-lg-8 col-xl-8">
            <div class="card-box">
                <h3 class="page-title mb-3"><b>Update Profile</b></h3>

                <form action="{{ route('board.profile.update',$user->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="row">
                            <div class="col-md-6 form-group">
                                <label for="first_name">Board Name<span class="text-danger">*</span></label>
                                <input type="text" name="first_name" parsley-trigger="change" value="{{$user->first_name}}" required placeholder="Enter Board name" class="form-control" id="first_name">
                                @error('first_name')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                          
                    </div>

                    <div class="row">
                            <div class="col-md-6 form-group">
                                <label for="email">Email address</label>
                                <input type="email" name="email" parsley-trigger="change" value="{{$user->email}}" placeholder="Enter email" class="form-control" id="email" readonly>
                                @error('email')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-6 form-group">
                                <label for="phone">Phone</label>
                                <input type="text" name="phone" parsley-trigger="change" value="{{$user->phone_formatted}}" placeholder="9999999999" class="form-control" id="phone"  readonly>
                                @error('phone')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                    </div>
                    <label for="image">Profile Picture<span class="text-danger">*</span></label>
                    <div class="col-6">
                            <div class="form-group">
                                <input type="file" data-parsley-trigger="change"  data-parsley-max-file-size="5" data-parsley-filemimetypes="image/jpeg, image/png" accept="image/*" data-parsley-file-mime-types-message="Only allowed jpeg & png files" onchange="readURL1(this);" id="inputGroupFile04" name="profile_picture" class="custom-file-input" />
                                <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                                @error('profile_picture')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                             
                    </div>

                    <div class="col-lg-6">
                            <div class="form-group">
                            @php
                                $default = '/images/default.png';
                            @endphp
                                <img class="border rounded p-0"  src="{{env('AWS_S3_URL').$user['profile_picture']}}" onerror="this.src='{{$default}}'" alt="your image" style="height: 130px;width: 130px; object-fit: cover;" id="blah1"/>
                            </div>
                    </div>

                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Submit
                        </button>
                        <button type="reset" class="btn btn-secondary waves-effect m-l-5">
                            Reset
                        </button>
                    </div>

                </form>

            </div> <!-- end card-box-->

        </div> <!-- end col -->
    </div>
    <div class="row">
        <div class="col-lg-4 col-xl-4">


        </div> <!-- end col-->

        <div class="col-lg-8 col-xl-8">
            <div class="card-box">
                <h3 class="page-title mb-3"><b>Change Password</b></h3>
                <form action="{{ route('board.change.password',$user->id) }}" method="POST">
                @csrf
                    <div class="form-group">
                        <label for="product-summary">Current Password</label>
                        <!-- <textarea class="form-control" id="product-summary" rows="1" placeholder="Please enter password" name="correct_answer">{{ old('correct_answer') }}</textarea> -->
                        <input type="password" name="current_password" class="form-control" >
                        @error('current_password')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                    </div>

                    <div class="form-group">
                        <label for="product-summary">New Password</label>
                        <!-- <textarea class="form-control" id="product-summary" rows="1" placeholder="Please enter password" name="correct_answer">{{ old('correct_answer') }}</textarea> -->
                        <input type="password" name="new_password" class="form-control" >
                        @error('new_password')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                    </div>

                    <div class="form-group">
                        <label for="product-summary">Confirm New Password</label>
                        <!-- <textarea class="form-control" id="product-summary" rows="1" placeholder="Please enter password" name="correct_answer">{{ old('correct_answer') }}</textarea> -->
                        <input type="password" name="confirm_new_password" class="form-control" >
                        @error('confirm_new_password')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                    </div>

                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Submit
                        </button>
                        <button type="reset" class="btn btn-secondary waves-effect m-l-5">
                            Reset
                        </button>
                    </div>

                </form>

            </div> <!-- end card-box-->

        </div> <!-- end col -->
    </div>
</div>

@endsection
@section('script')
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});

function readURL1(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah1').attr('src', e.target.result);
            $('.blah1').attr('href', e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
    }
} 
</script>
@endsection	