routes/web.php
| contains the "web" middleware group. Now create something great!
|
 */


Route::get('education-outreach', 'Api\DocumentController@education_outreach');
Route::get('about-us', 'Api\DocumentController@about_us');
Route::get('contact-us', 'Api\DocumentController@contact_us');
Route::get('internet-based-ads', 'Api\DocumentController@internet_based_ads');
Route::get('privacy-notice', 'Api\DocumentController@privacy_notice');
Route::get('term-of-service', 'Api\DocumentController@term_of_service');

Route::post('add-channel-id', 'CommonController@add_channel_id');
Route::get('account-activation/{id}', 'CommonController@account_activation');
Route::any('create/password/{id}/{token}', 'CommonController@craete_password')->name('create.password');
Route::get('auth-account-activation/{id}', 'CommonController@auth_account_activation');

Route::post('forgot/password', 'CommonController@forgot_password')->name('forgot_password');
Route::get('store-forgot-password', 'CommonController@store_forgot_password')->name('store.forgot');
Route::get('board-forgot-password', 'CommonController@board_forgot_password')->name('board.forgot');


Route::get('add-channel-id', 'CommonController@add_channel_id');
Route::get('terms-conditions', 'CommonController@terms_conditions');
Route::get('privacy-policy', 'CommonController@privacy_policy');
Route::get('logs/{id}', 'CommonController@activity_log');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function () {

    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');

    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/show/{id}', 'UserController@show')->name('user.show');
    Route::get('users/edit/{id}', 'UserController@edit')->name('user.edit');
    Route::put('users/update/{id}', 'UserController@update')->name('user.update');
    Route::get('users/destroy/{id}', 'UserController@edit')->name('user.destroy');
    Route::post('active_deactive','UserController@active_deactive')->name('active_deactive');

    Route::post('active_deactive_school','SchoolController@active_deactive_school')->name('active_deactive_school');

    Route::post('active_deactive_genre','CategoryController@active_deactive_genre')->name('active_deactive_genre');
      
    Route::resource('category',CategoryController::class);
    Route::resource('season',SeasonController::class);
    Route::resource('ratings',AgeRatingController::class);
    Route::resource('tags',TagController::class);
    Route::resource('artist',ArtistController::class);
    Route::resource('genre',GenreController::class);
    Route::resource('cast',CastTypeController::class);
    Route::resource('plan',PlanController::class);  
    Route::resource('attribute',AttributeController::class);  
    Route::resource('measurement',MeasurementController::class);    
    Route::resource('contactus',ContactUsController::class);    
    Route::resource('issue',IssueController::class);    
    Route::resource('grade',GradeController::class);    
    Route::resource('orders',OrderController::class);  
    Route::resource('content',ContentController::class);    
    Route::resource('video',VideoController::class);    
    Route::resource('faq',FaqController::class);    
    Route::resource('feedback',FeedbackController::class);    
    
    Route::any('adv_content_change', 'ContentController@adv_content_change')->name('adv_content_change');
    Route::any('child_adv_content_change', 'ContentController@child_adv_content_change')->name('child_adv_content_change');
    Route::get('get_season_data', 'VideoController@get_season_data')->name('get_season_data');   
    Route::post('trailer_file_upload', 'ContentController@trailer_file_upload')->name('trailer_file_upload');   
    Route::post('chunk_file_upload', 'VideoController@chunk_file_upload')->name('chunk_file_upload');   
    Route::post('active_deactive_faq','FaqController@active_deactive_faq')->name('active_deactive_faq');

    Route::get('plan/manageattr/{id}', 'PlanController@manageattr')->name('plan.manageattr');   
    Route::post('plan/attr_update/{id}', 'PlanController@attr_update')->name('plan.attr_update');   
    
    Route::post('product/addstore/{id}', 'ProductController@addstore')->name('product.addstore');   
    Route::get('remove_product_store/{id}', 'ProductController@remove_product_store')->name('remove_product_store');   
    Route::post('save_product_store', 'ProductController@save_product_store')->name('save_product_store');   
    Route::post('active_deactive_product','ProductController@active_deactive_product')->name('active_deactive_product');
    Route::post('get_image','ProductController@get_image')->name('get_image');

    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');
    
    Route::get('reported/issue','IssueController@reported_issue_index')->name('reported.issue');
    Route::get('bulk/notification',[NotificationController::class,'index'])->name('bulk.index');
    Route::post('bulk/notification',[NotificationController::class,'store'])->name('bulk.store');
    
    Route::get('system/config','SystemConfigController@index')->name('system.config');
    Route::post('system/config/submit','SystemConfigController@update')->name('system.config.submit');
    Route::post('system/config/backup','SystemConfigController@update')->name('system.config.backup');
    Route::post('system/config/download','SystemConfigController@update')->name('system.config.download');
    Route::post('system/config/delete_backup','SystemConfigController@update')->name('system.config.delete_backup');
    
    Route::get('app/config','SystemConfigController@app')->name('app.config');
    Route::post('app/config/submit','SystemConfigController@submit_app')->name('app.config.submit');

    Route::get('report/all_report','ReportController@index')->name('report.all');

    Route::get('order/all_orders','OrderController@all_orders')->name('order.all');

    Route::get('order/create_order','OrderController@create_order')->name('order.create');

    Route::post('order/get_user','OrderController@get_user')->name('order.get_user');
    Route::post('order/get_meal','OrderController@get_meal')->name('order.get_meal');
    Route::post('order/get_meal_details','OrderController@get_meal_details')->name('order.get_meal_details');
    Route::post('order/book_meal','OrderController@book_meal')->name('order.book_meal');

    Route::get('order/refund','OrderController@refund')->name('order.refund');
    Route::get('order/all_orders/view/{id}','OrderController@all_orders_view')->name('order.all.view');
    Route::post('refund','OrderController@refund_test')->name('refund');

    Route::any('send-mail-customer',[SendMailController::class,'customer'])->name('mail.customer');
    Route::any('send-notification-customer',[SendMailController::class,'customer_notification'])->name('notification.customer');

    Route::any('terms-conditions',[CMSController::class,'terms_conditions'])->name('terms_conditions');
    Route::any('privacy-policy',[CMSController::class,'privacy_policy'])->name('privacy_policy');
});
Route::group(['namespace' => 'Board', 'prefix' => 'board', 'as' => 'board.', 'middleware' => ['auth', 'board']], function () {
    
    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');
    
    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('active_deactive_category','CategoryController@active_deactive_category')->name('active_deactive_category');
    Route::resource('category', CategoryController::class);
    Route::resource('store', StoreController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('product', ProductController::class);
    Route::resource('orders',OrderController::class);
    Route::resource('meal', MealController::class);
    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');

    Route::get('report/all_report','ReportController@all_report')->name('report.all');
    
    Route::get('order/all','OrderController@all')->name('order.all');
    Route::get('order/all/view/{id}','OrderController@all_orders_view')->name('order.all.view');

    Route::get('order/inprocess','OrderController@inprocess')->name('order.inprocess');
    Route::get('order/inprocess/view/{id}','OrderController@inprocess_view')->name('order.inprocess.view');
    Route::get('order/inprocess/edit/{id}','OrderController@inprocess_edit')->name('order.inprocess.edit');
    Route::post('order/inprocess/item/update','OrderController@item_update')->name('order.item.update');
    Route::post('order/inprocess/date/update','OrderController@date_update')->name('order.date.update');

     Route::post('active_deactive_product','ProductController@active_deactive_product')->name('active_deactive_product');
     Route::post('active_deactive_meal','MealController@active_deactive_meal')->name('active_deactive_meal');

    Route::post('pending_order','OrderController@pending_order')->name('pending_order');

    Route::get('order/completed','OrderController@completed')->name('order.completed');
    Route::get('order/completed/view/{id}','OrderController@completed_view')->name('order.completed.view');

    Route::get('order/fail','OrderController@fail')->name('order.fail');

app/Models/Orders.php
<?php



namespace App\Models;



use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

use DB;
use Illuminate\Database\Eloquent\SoftDeletes;

class Orders extends Model

{

    use HasFactory, SoftDeletes;

    protected $table = 'orders';

    protected $fillable = [
        'id',
        'user_id',
        'store_id',
        'cart_id',
        'sub_total',
        'total',
        'tax',
        'pickup_method',
        'transaction_id',
        'gateway_trans_id',
        'name',
        'number',
        'pickup_notes',
        'vehicle_description',
        'reached',
        'status'
    ];



    /**

     * The attributes that should be hidden for arrays.

     *

     * @var array

     */

    protected $hidden = [

        'updated_at'

    ];



    protected $appends = array('store_name','customer_name','order_on_formatted','current_status','store_name','reached_on_formatted','user_type','board_name','board_id');



    public function getStoreNameAttribute()

    {

        $user = User::find($this->store_id);  

        return $user->first_name;  

    }

    public function getBoardNameAttribute()

    {

        $user = User::find($this->store_id);  
        if($user)
        {

            $board = User::find($user->parent_id);  
            if($board)
            {
                return $board->first_name;  

            }
        }
        return '';

    }

    public function getBoardIdAttribute()

    {

        $user = User::find($this->store_id);  
        return $user->parent_id;

    }



    public function getStoreAddressAttribute()

    {

        $user = User::find($this->store_id);  

        return $user->address;  

    }
     public function getUserTypeAttribute()

    {

        $user = DB::table('users')->whereId($this->user_id)->first();  

        if(isset($user)){

            return $user->user_type;   

        }else{

            return $this->user_id;   

        }

    }


    public function getCustomerNameAttribute()

    {

        $user = DB::table('users')->whereId($this->user_id)->first();  

        if(isset($user)){

            return $user->first_name.' '.$user->last_name;   

        }else{

            return $this->user_id;   

        }

    }

    public function getOrderOnFormattedAttribute()

    {

        if(isset($this->created_at)){

            $created_at_obj = Carbon::createFromFormat('Y-m-d H:i:s', $this->created_at);

            return $created_at_obj->format('m-d-Y h:i A');

        }else{

            return '';

        }

    }

     public function getReachedOnFormattedAttribute()

    {

        if(isset($this->reached)){

            $reached = Carbon::createFromFormat('Y-m-d H:i:s', $this->reached);

            return $reached->format('m-d-Y h:i A');

        }else{

            return '';

        }

    }



    public function getCurrentStatusAttribute()

    {
        $order_status = config('app.order_status');
        return $order_status[$this->status];
    }



    public function customer() {

        return $this->hasOne('App\Models\User', 'id', 'customer_id');

	}

    public function order_products()
    {
        return $this->hasMany('App\Models\OrdersProduct', 'order_id', 'id');
    }

    public function store()
    {
        return $this->belongsTo('App\Models\User', 'store_id', 'id');
    }

}

resources/views/admin/pages/order/index.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('order')}}
                </div>
                <h4 class="page-title">{{$dateTableTitle}}</h4>
            </div>
            <div class="btn-group float-right mt-2 mb-2">
            </div>
        </div>
    </div>
    @include('admin.include.flash-message')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body" >
                     <form class="form-inline mb-2" method="post" action="{{route('admin.orders.index')}}" id="filter-form">

                        <div class="form-group">
                            <select class="form-control select2" name="store_id" id="store_id">
                                 <option value="All">All Store</option>
                                @foreach($store_data as $store)
                                    <option value="{{$store->id}}">{{$store->first_name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group mx-2">
                            <select class="form-control select2" name="pickup_method" id="pickup_method">
                                <option value="All">All Pickup Method</option>
                                <option value="InStore">InStore</option>
                                <option value="CurbSide">CurbSide</option>
                            </select>
                        </div>

                        <div class="form-group ">
                            <select class="form-control select2" name="status" id="order_status">
                                <option value="All">All Order Status</option>
                             
                                @foreach(config('app.order_status') as $order)
                                <option value="{{$order}}">{{$order}}</option>
                                @endforeach
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light ml-1" ><i class="fa fa-search" name="search"></i></button>
                    </form>
                    @include('admin.include.table')
                </div>
            </div>  
        </div>
    </div>
</div>
<!-- Modal -->
<div id="exampleModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Send Push Notification</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body p-2">
                <form id="form-inline" action="">
                <input type="hidden" id="user_id" value="">
                <input type="hidden" id="order_id" value="">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Title</label>
                            <input type="text" parsley-trigger="change" value="{{old('title')}}" required class="form-control" name="title" id="field-3" placeholder="Enter Title">
                             <input type="hidden" parsley-trigger="change" value="{{old('order_id')}}" required class="form-control" name="order_id" id="order_id" placeholder="Enter order_id" >
                        </div>
                    </div>
                </div>
              
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <label for="notification" class="control-label">Message</label>
                            <textarea class="form-control" id="notification" placeholder="Enter Message" name="notification" parsley-trigger="change" value="{{old('message')}}" required></textarea>
                        </div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-info waves-effect waves-light" id="send" data-user-id="" data-order-id="" >Send </button>
            </div>
            </div>
        </div>
    </div>
</div><!-- /.modal -->


@endsection
@section('script')

@include('admin.include.table_script')
<script src="{{ URL::asset('assets/js/order.js')}}"></script>

@endsection     

resources/views/admin/pages/order/view.blade.php
@extends('admin.layouts.master')
@section('content')                             
<!-- Start Content-->
<div class="container-fluid">
    
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    {{ Breadcrumbs::render('vieworder')}}
                </div>
                <h4 class="page-title">Invoice</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 

    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <!-- Logo & title -->
                <div class="clearfix">
                    <div class="float-left">
                        <img src="assets/images/logo-dark.png" alt="" height="20">
                    </div>
                    <div class="float-right">
                        <h4 class="m-0 d-print-none">Invoice</h4>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="mt-3">
                            <img src="{{url('assets/images/invoicelogo.png')}}" style="height:10px;width:10px;height: 79px;width: 120px;margin-top:-58px;margin-bottom: 31px;">
                        </div>  

                    </div><!-- end col -->
                    <div class="col-md-4 offset-md-2">

                        <div class="mt-3 float-right">
                            <p class="m-b-10"><strong>Order No. : </strong> <span class="float-right">#{{$order->id}} </span></p>
                            <p class="m-b-10"><strong>Order Date Time : </strong> <span class="float-right"> &nbsp;&nbsp;&nbsp;&nbsp; {{$order->order_on_formatted}}</span></p>
                            <p class="m-b-10"><strong>Order Status :  </strong> 
                                <span class="float-right"><span class="badge badge-primary">{{$order->current_status}}</span></span>
                            </p>
                            @if($order->reached != Null)
                            <p class="m-b-10"><strong>Reached At : </strong> <span class="float-right">{{$order->reached_on_formatted}} </span></p>
                            @else
                            <p class="m-b-10"></p>
                            @endif
                            @if($order->pickup_method=='1')
                            <p class="m-b-10"><strong>PickUp Type : </strong> <span class="float-right">Instore </span></p>
                            @else($order->pickup_method=='2')
                            <p class="m-b-10"><strong>PickUp Type : </strong> <span class="float-right">CurbSide </span></p>
                            @endif
                            @if($order->user_type == '0')
                            <p class="m-b-10"><strong>User Type : </strong> <span class="float-right">Retailer  </span></p>
                            @else($order->user_type=='1')
                            <p class="m-b-10"><strong>User Type : </strong> <span class="float-right">Business  </span></p>
                            @endif
                             <!-- <p class="m-b-10"><strong>Store Name : </strong> <span class="float-right">{{$order->store_name}}  </span></p> -->
                            <p class="m-b-10"><strong>Customer Name : </strong> <span class="float-right"><a href="{{route('admin.user.show',$order->user_id)}}" target="_blank">{{$order->customer_name}} </a> </span></p>

                        </div>
                    </div><!-- end col -->
                </div>
                <!-- end row -->

                <div class="row mt-3">
                    <div class="col-sm-6">
                        @if($order->vehicle_description!='')
                        <strong>Vehicle Description</strong>
                        <address>
                            {{$order->vehicle_description}}<br>
                        </address>
                        @else
                        <h6></h6>
                        <address>
                            <br>
                        </address>
                        @endif

                    </div> <!-- end col -->

                    <div class="col-sm-6 text-right">
                        <strong>Store </strong>
                        <address>
                            <a href="{{route('admin.store.show',$order->store_id)}}" target="_blank">{{$order->store_name}}</a> <br>
                            {{$order->store_address}}
                        </address>
                    </div> <!-- end col -->
                </div> 
                <!-- end row -->
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table mt-4 table-centered">
                                <thead>
                                <tr><th>Image</th>
                                    <th>Products</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                    <th class="text-right">Total</th>
                                </tr></thead>

                                <tbody>
                                @if(isset($products) && count($products) > 0)
                                @foreach ($products as $products)
                                <tr>
                                    <td><img src="{{$products->varient->picture}}" style="height: 72px;object-fit: scale-down;"></td>
                                      <td>{{$products->product_name}}<br>{{$products->varient->quantity}}&nbsp;{{$products->varient->measurement}}</td>
                                    <td>{{$products->qty}}</td>
                                    <td>${{$products->price}}</td>
                                    <td class="text-right">${{number_format((float)$products->price * $products->qty, 2, '.', '')}}</td>
                                </tr>
                                @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div> <!-- end table-responsive -->
                    </div> <!-- end col -->
                </div>
                <!-- end row -->

                <div class="row">
                    <div class="col-sm-6">
                        <div class="clearfix pt-5">
                            <strong class="d-block">Name:</strong>

                            <small class="text-muted">
                                {{$order->name}}
                            </small>
                            <br>
                            <strong class="d-block">Number:</strong>

                            <small class="text-muted">
                                {{$order->number}}
                            </small>
                            <br>
                            @if($order->pickup_notes!='')
                            <strong class="d-block">Pickup Notes:</strong>

                            <small class="text-muted">
                                {{$order->pickup_notes}}
                            </small>
                            @else
                            <strong class="text-muted"></strong>
                            <small class="text-muted">
                                
                            </small>
                            @endif
                        </div>
                    </div> <!-- end col -->
                    <div class="col-sm-6">
                        <div class="float-right">
                            <p><b>Sub total:</b> <span class="float-right">${{$order->sub_total}}</span></p>
                            <p><b>Tax:</b> <span class="float-right">${{$order->tax}}</span></p>
                            
                            <h3>${{$order->total}} USD</h3>
                        </div>
                        <div class="clearfix"></div>
                    </div> <!-- end col -->
                </div>
                <!-- end row -->

                <div class="mt-4 mb-1">
                    <div class="text-right d-print-none">
                        <a href="javascript:window.print()" class="btn btn-primary waves-effect waves-light"><i class="mdi mdi-printer mr-1"></i> Print</a>
                       
                    </div>
                </div>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>
    <!-- end row --> 
    
</div> <!-- container -->
@endsection